#!/bin/bash

tmp_dir=~/wrk/tmp
tmp_file_path=$tmp_dir/tmp.txt

cmdsub="$1"

#if   test -z $cmdsub
if   test -p /dev/stdin
then
  cat - >> $tmp_file_path

#elif test $cmdsub = 'paste'
#then
else
  clp_str=$( tail -n 1 $tmp_file_path )
  echo $clp_str

  READLINE_LINE="$READLINE_LINE $clp_str"
fi

