#!/bin/bash

tmp_dir=~/wrk/tmp
tmp_file_path=$tmp_dir/tmp.txt

cmdsub="$1"

if   test -p /dev/stdin
then
  #cat - >> $tmp_file_path
  cat - > $tmp_file_path

elif test -z $cmdsub
then
  #clp_str=$( cat $tmp_file_path )
  #READLINE_LINE="$READLINE_LINE $clp_str"

  clp_str=$( cat $tmp_file_path )
  echo $clp_str

elif test $cmdsub = 'echo'
then
  clp_str=$( cat $tmp_file_path )
  echo $clp_str

elif test $cmdsub = 'clr'
then
  :> $tmp_file_path

else
  echo "cmdsub : $cmdsub ?"
fi

