#!/bin/bash

# function mb_cnv_alpha

srch_l='ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ'
rpl_l='abcdefghijklmnopqrstuvwxyz'

srch_u='ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ'
rpl_u='ABCDEFGHIJKLMNOPQRSTUVWXYZ'

cat -                |\
sed_y $srch_l $rpl_l |\
sed_y $srch_u $rpl_u



