#!/bin/bash

dir=~/wrk

cmdsub="$1"

if   test $cmdsub = 'cd'
then
  psh $dir

elif test $cmdsub = 'fd'
then
  if test -z $2
  then
    fd -e md '' $dir
  else
    fd -e md '' $dir | rg $2
  fi

elif test $cmdsub = 'rg'
then
  #rg -N -g '*.md' "$2" $dir/

  ptn="$2"
  opt="$3"

  if test "$opt" = 'vi'
  then
    vi -p $( rg -Nw -B 1 -l -g '*.md' "$ptn" $dir/ )
  else
    rg -Nw -B 1 $opt -g '*.md' "$ptn" $dir/
  fi

elif test $cmdsub = 'pw'
then
  prj_dir=$dir/prj

  rg -N -w -g '*.md' 'pw' $prj_dir/ -B1 -A1

elif test $cmdsub = 'vi'
then
  if test -z $2
  then
    vi -p -c ":cd $dir"
  else
    vi -p -c ":cd $dir" $( fd -e md '' $dir | rg $2 )
  fi

elif test $cmdsub = 'slf'
then
  slf_dir=~/wrk/cnf/sh/bash/cmd
  slf_path=$slf_dir/memo

  vi -p $slf_path

else
  echo cmdsub : $cmdsub ?
fi

