
local scheme_lst = {}

-- win

scheme_lst.win = {}
scheme_lst.win.recommend = {}
scheme_lst.win.recommend.h = {
  'Snazzy (base16)'                       , -- < h
  'Hurtado'                               ,
  'SynthWave (Gogh)'                      ,
  'UltraViolent'                          ,
  'niji'                                  ,
  'Borland'                               ,
  'VibrantInk'                            ,
  'Synthwave (Gogh)'                      ,
  'tokyonight'                            ,
  'Everblush (Gogh)'                      ,
  'AyuMirage (Gogh)'                      ,
  'arcoiris'                              ,
  'MonokaiPro (Gogh)'                     ,
  'Dracula+'                              ,
  'Tomorrow Night Blue'                   ,
  'Horizon Dark (Gogh)'                   ,
  'PaperColorDark (Gogh)'                 ,
  'Material (base16)'                     ,
  'Chalk (dark) (terminal.sexy)'          ,
  'Tokyo Night Storm'                     ,
  'Duotone Dark'                          ,
}
scheme_lst.win.recommend.m = {
  'BlueDolphin'                           ,
  'Builtin Pastel Dark'                   ,
  'Dracula (Gogh)'                        ,
  'Ef-Deuteranopia-Dark'                  ,
  'Ef-Duo-Dark'                           ,
  'Ef-Elea-Dark'                          ,
  'Ef-Rosa'                               ,
  'Ef-Trio-Dark'                          ,
  'Espresso Libre'                        ,
  'IdleToes (Gogh)'                       ,
  'Jellybeans'                            ,
  'Monokai Remastered'                    ,
  'NightLion v2'                          ,
  'OneHalfBlack (Gogh)'                   ,
  'Oxocarbon Dark (Gogh)'                 ,
  'PaperColorDark (Gogh)'                 ,
  'Purple People Eater (Gogh)'            ,
  'Purple Rain'                           ,
  'Red Alert (Gogh)'                      ,
  'Red Alert'                             ,
  'Relaxed'                               ,
  'Seti UI (base16)'                      ,
  'Smyck (Gogh)'                          ,
  'Windows High Contrast (base16)'        ,
  'iTerm2 Light Background'               ,
  'iTerm2 Smoooooth'                      ,
  'iTerm2 Tango Dark'                     ,
  'kanagawabones'                         ,
  'Nucolors (terminal.sexy)'              ,
  'Moonfly (Gogh)'                        ,
  'Poimandres'                            ,
  'Paul Millr (Gogh)'                     ,
  'Broadcast'                             ,
  'Bright (base16)'                       ,
  'Chalkboard (Gogh)'                     ,
  'catppuccin-macchiato'                  ,
}
scheme_lst.win.excld = {
  '3024 Day (Gogh)'                       ,
  'Apple Classic'                         ,
  'Ashes (light) (terminal.sexy)'         ,
  'Atelier Heath Light (base16)'          ,
  'Atelier Plateau Light (base16)'        ,
  'Atelier Savanna (base16)'              ,
  'Atelierdune (dark) (terminal.sexy)'    ,
  'Atelierforest (light) (terminal.sexy)' ,
  'Atelierheath (dark) (terminal.sexy)'   ,
  'Atelierseaside (light) (terminal.sexy)',
  'AyuLight (Gogh)'                       ,
  'Belafonte Day'                         ,
  'Bitmute (terminal.sexy)'               ,
  'Black Metal (Dark Funeral) (base16)'   ,
  'Black Metal (Khold) (base16)'          ,
  'Black Metal (Mayhem) (base16)'         ,
  'Bluloco Light (Gogh)'                  ,
  'BlulocoZshLight (Gogh)'                ,
  'Brewer (light) (terminal.sexy)'        ,
  'Brogrammer'                            ,
  'C64 (Gogh)'                            ,
  'C64'                                   ,
  'CGA'                                   ,
  'CLRS'                                  ,
  'Canvased Pastel (terminal.sexy)'       ,
  'Catch Me If You Can (terminal.sexy)'   ,
  'Catppuccin Latte (Gogh)'               ,
  'Ciapre (Gogh)'                         ,
  'Circus (base16)'                       ,
  'Clrs (Gogh)'                           ,
  'Cobalt Neon (Gogh)'                    ,
  'Cobalt Neon'                           ,
  'Cobalt2'                               ,
  'Colorful Colors (terminal.sexy)'       ,
  'Count Von Count (terminal.sexy)'       ,
  'CrayonPonyFish'                        ,
  'DanQing Light (base16)'                ,
  'Dark Pastel (Gogh)'                    ,
  'Dawn (terminal.sexy)'                  ,
  'Digerati (terminal.sexy)'              ,
  'Edge Light (base16)'                   ,
  'Ef-Elea-Light'                         ,
  'Ef-Frost'                              ,
  'Ef-Tritanopia-Light'                   ,
  'Eldorado dark (terminal.sexy)'         ,
  'Embers (base16)'                       ,
  'Espresso Libre (Gogh)'                 ,
  'Fishbone (terminal.sexy)'              ,
  'Freya (Gogh)'                          ,
  'FrontEndDelight'                       ,
  'FrontendDelight (Gogh)'                ,
  'Galaxy'                                ,
  'Github'                                ,
  'Google (light) (terminal.sexy)'        ,
  'Google Light (Gogh)'                   ,
  'Google Light (base16)'                 ,
  'GoogleLight (Gogh)'                    ,
  'Grape'                                 ,
  'Grass'                                 ,
  'Grayscale (light) (terminal.sexy)'     ,
  'Greenscreen (dark) (terminal.sexy)'    ,
  'Gruvbox Light'                         ,
  'GruvboxLight'                          ,
  'HaX0R_GR33N'                           ,
  'Hacktober'                             ,
  'Hardcore (base16)'                     ,
  'Harmonic16 Dark (base16)'              ,
  'Harmonic16 Light (base16)'             ,
  'Harper (Gogh)'                         ,
  'Harper'                                ,
  'HemisuLight (Gogh)'                    ,
  'Highway'                               ,
  'Homebrew (Gogh)'                       ,
  'Humanoid light (base16)'               ,
  'Hybrid'                                ,
  'IR Black (base16)'                     ,
  'Ibm 3270 (High Contrast) (Gogh)'       ,
  'Ic Orange Ppl (Gogh)'                  ,
  'Icy Dark (base16)'                     ,
  'Invisibone (terminal.sexy)'            ,
  'JWR dark (terminal.sexy)'              ,
  'Jackie Brown'                          ,
  'Japanesque'                            ,
  'Jup (Gogh)'                            ,
  'Kasugano (terminal.sexy)'              ,
  'Lavandula (Gogh)'                      ,
  'Light White (terminal.sexy)'           ,
  'LiquidCarbonTransparent'               ,
  'Lost Woods (terminal.sexy)'            ,
  'Low Contrast (terminal.sexy)'          ,
  'Lunaria Light (Gogh)'                  ,
  'LunariaDark (Gogh)'                    ,
  'LunariaLight (Gogh)'                   ,
  'Man Page'                              ,
  'Mar (Gogh)'                            ,
  'Material (Gogh)'                       ,
  'MaterialDark'                          ,
  'Mikazuki (terminal.sexy)'              ,
  'Mirage'                                ,
  'Modus-Operandi-Deuteranopia'           ,
  'Mona Lisa (Gogh)'                      ,
  'Mono (terminal.sexy)'                  ,
  'Mono Green (Gogh)'                     ,
  'Mono White (Gogh)'                     ,
  'Mono Yellow (Gogh)'                    ,
  'Monokai (light) (terminal.sexy)'       ,
  'Monokai Vivid'                         ,
  'MonokaiDark (Gogh)'                    ,
  'N0Tch2K (Gogh)'                        ,
  'Nature Suede (terminal.sexy)'          ,
  'Navy and Ivory (terminal.sexy)'        ,
  'Nep (Gogh)'                            ,
  'Neutron'                               ,
  'NightLion v1'                          ,
  'Nighty (Gogh)'                         ,
  'Nord Light (Gogh)'                     ,
  'One Light (base16)'                    ,
  'OneHalfLight'                          ,
  'PaperColorLight (Gogh)'                ,
  'Paraiso Dark (Gogh)'                   ,
  'Pop (base16)'                          ,
  'Porple (base16)'                       ,
  'Pretty and Pastel (terminal.sexy)'     ,
  'Pro (Gogh)'                            ,
  'Purpledream (base16)'                  ,
  'Rasi (terminal.sexy)'                  ,
  'Raycast_Light'                         ,
  'RoséPine (Gogh)'                       ,
  'Rydgel (terminal.sexy)'                ,
  'Sagelight (base16)'                    ,
  'Shaman (Gogh)'                         ,
  'Shapeshifter (base16)'                 ,
  'Shapeshifter (dark) (terminal.sexy)'   ,
  'Shel (Gogh)'                           ,
  'Silk Light (base16)'                   ,
  'Slate (Gogh)'                          ,
  'Solarized Dark (Gogh)'                 ,
  'Solarized Dark - Patched'              ,
  'Solarized Light (Gogh)'                ,
  'Spacegray (Gogh)'                      ,
  'Spiderman'                             ,
  'Sundried'                              ,
  'Synth Midnight Terminal Light (base16)',
  'Tangoesque (terminal.sexy)'            ,
  'Terminal Basic (Gogh)'                 ,
  'Terminal Basic'                        ,
  'TerminixDark (Gogh)'                   ,
  'Tokyo Night Day'                       ,
  'TokyoNightLight (Gogh)'                ,
  'Tomorrow (Gogh)'                       ,
  'Treehouse'                             ,
  'Twilight (dark) (terminal.sexy)'       ,
  'Ubuntu'                                ,
  'Unikitty Light (base16)'               ,
  'Unsifted Wheat (terminal.sexy)'        ,
  'Ura (Gogh)'                            ,
  'Vacuous 2 (terminal.sexy)'             ,
  'Vag (Gogh)'                            ,
  'Vice Alt (base16)'                     ,
  'Violet Light'                          ,
  'Vs Code Light+ (Gogh)'                 ,
  'Windows 95 Light (base16)'             ,
  'Wryan'                                 ,
  'darkermatrix'                          ,
  'darkmatrix'                            ,
  'dayfox'                                ,
  'mono-red (Gogh)'                       ,
  'mono-yellow (Gogh)'                    ,
  'nighty (Gogh)'                         ,
  'summercamp (base16)'                   ,
  'vimbones'                              ,
  'zenbones_light'                        ,
  'Rippedcasts (Gogh)'                    ,
  'GruvboxDarkHard'                       ,
  'Breeze'                                ,
  'ibm3270 (Gogh)'                        ,
  'Darkside'                              ,
  'Vaughn'                                ,
  'Lunaria Dark (Gogh)'                   ,
  'IBM3270(HighContrast) (Gogh)'          ,
  'shades-of-purple'                      ,
  'Thayer Bright'                         ,
  'iTerm2 Default'                        ,
  'Black Metal (Burzum) (base16)'         ,
  'Gigavolt (base16)'                     ,
  'Bamboo Light'                          ,
  'Subliminal'                            ,
  'iceberg-light'                         ,
  'Default (light) (terminal.sexy)'       ,
  'Londontube (light) (terminal.sexy)'    ,
  'hund (terminal.sexy)'                  ,
  'Ollie (Gogh)'                          ,
  'Gruvbox dark, hard (base16)'           ,
  'RedAlert (Gogh)'                       ,
  'Solarized Dark Higher Contrast'        ,
  'Atelier Dune (base16)'                 ,
  'Neopolitan'                            ,
  'Atlas (base16)'                        ,
  'Color Star (terminal.sexy)'            ,
  'Everforest Light (Gogh)'               ,
  'Neutron (Gogh)'                        ,
  'BelafonteDay (Gogh)'                   ,
  'HaX0R_BLUE'                            ,
}

-- mac

scheme_lst.mac = {}
scheme_lst.mac.recommend = {}
scheme_lst.mac.recommend.h = {
  'Framer (base16)'                       ,
}
scheme_lst.mac.recommend.m = {
  'IrBlack (Gogh)'                        ,
  'rebecca'                               ,
  'shades-of-purple'                      ,
  'OneHalfBlack (Gogh)'                   ,
}
scheme_lst.mac.excld = {
  'PaperColor Dark (base16)'              ,
  'thwump (terminal.sexy)'                ,
  'Cupertino (base16)'                    ,
  'Elementary'                            ,
  'Isotope (light) (terminal.sexy)'       ,
  'Neutron (Gogh)'                        ,
  'Geohot (Gogh)'                         ,
  'Ic Orange Ppl (Gogh)'                  ,
  'Jackie Brown (Gogh)'                   ,
  'Ef-Melissa-Light'                      ,
  'Rosé Pine Dawn (Gogh)'                 ,
  'Edge Light (base16)'                   ,
  'alacritty'                             ,
  'VisiBone (terminal.sexy)'              ,
  'Liquid Carbon (Gogh)'                  ,
  'carbonfox'                             ,
  'EspressoLibre (Gogh)'                  ,
  'Grass'                                 ,
  'Atelier Plateau (base16)'              ,
  'Ef-Tritanopia-Light'                   ,
  'Builtin Tango Light'                   ,
  'HaX0R_BLUE'                            ,
  'Deafened (terminal.sexy)'              ,
  'Windows High Contrast Light (base16)'  ,
  'Bespin (base16)'                       ,
  'Freya (Gogh)'                          ,
  'FrontendFunForrest (Gogh)'             ,
  'Nightlion V1 (Gogh)'                   ,
  'LunariaLight (Gogh)'                   ,
  'gooey (Gogh)'                          ,
  'Brewer (light) (terminal.sexy)'        ,
  'Atlas (base16)'                        ,
  'Sublette'                              ,
  'Grass (Gogh)'                          ,
  'One Dark (Gogh)'                       ,
  'Atelierlakeside (dark) (terminal.sexy)',
  'One Light (base16)'                    ,
  'Urple (Gogh)'                          ,
  'Icy Dark (base16)'                     ,
  'Colorful Colors (terminal.sexy)'       ,
  'Zenburn'                               ,
  'Dotshare (terminal.sexy)'              ,
  'Warm Neon (Gogh)'                      ,
  'Material'                              ,
  'BreathLight (Gogh)'                    ,
  'Nord Light (Gogh)'                     ,
  'iceberg-light'                         ,
  'Gruvbox light, medium (base16)'        ,
  'Gotham (Gogh)'                         ,
}

return scheme_lst

