
-- mac

local scheme_lst = {}

scheme_lst.mac = {}
scheme_lst.mac.recommend = {}
scheme_lst.mac.recommend.h = {
  'DanQing (base16)'                       ,
  'Dracula (base16)'                       ,
  'Framer (base16)'                        ,
  'Ir Black (Gogh)'                        ,
  'Rebecca (base16)'                       ,
  'astel White (terminal.sexy)'            ,
  'Subliminal'                             ,
}
scheme_lst.mac.recommend.m = {
  'Andromeda'                              ,
  'Brogrammer (Gogh)'                      ,
  'Darkside'                               ,
  'Ef-Melissa-Dark'                        ,
  'Equilibrium Dark (base16)'              ,
  'Everforest Dark (Gogh)'                 ,
  'Gogh (Gogh)'                            ,
  'Grandshell (terminal.sexy)'             ,
  'Humanoid dark (base16)'                 ,
  'IrBlack (Gogh)'                         ,
  'Material (base16)'                      ,
  'Mocha (base16)'                         ,
  'OneHalfBlack (Gogh)'                    ,
  'Orangish (terminal.sexy)'               ,
  'Peppermint (Gogh)'                      ,
  'Railscasts (base16)'                    ,
  'Raycast_Light'                          ,
  'Red Alert (Gogh)'                       ,
  'Seti (Gogh)'                            ,
  'Solarized Dark Higher Contrast (Gogh)'  ,
  'SweetTerminal (Gogh)'                   ,
  'Synth Midnight Terminal Dark (base16)'  ,
  'SynthwaveAlpha (Gogh)'                  ,
  'Tender (Gogh)'                          ,
  'VibrantInk'                             ,
  'ight Owl (Gogh)'                        ,
  'rebecca'                                ,
  'shades-of-purple'                       ,
  'summer-pop (Gogh)'                      ,
  'Classic Dark (base16)'                  ,
  'London Tube (base16)'                   ,
  'iceberg-dark'                           ,
  'Material (Gogh)'                        ,
  'Tomorrow Night Bright (Gogh)'           ,
  'MonokaiDark (Gogh)'                     ,
  'Banana Blueberry'                       ,
  'Mathias'                                ,
  'Ef-Elea-Dark'                           ,
  'SynthwaveAlpha'                         ,
  'Tomorrow Night Bright'                  ,
  'Londontube (dark) (terminal.sexy)'      ,
}
scheme_lst.mac.excld = {
  '3024Day (Gogh)'                         ,
  'AlienBlood'                             ,
  'Ashes (dark) (terminal.sexy)'           ,
  'Atelier Plateau (base16)'               ,
  'Atelierforest (light) (terminal.sexy)'  ,
  'Atelierlakeside (dark) (terminal.sexy)' ,
  'Atlas (base16)'                         ,
  'AtomOneLight'                           ,
  'AyuDark (Gogh)'                         ,
  'Batman'                                 ,
  'Belafonte Day (Gogh)'                   ,
  'Bespin (base16)'                        ,
  'Black Metal (Bathory) (base16)'         ,
  'Black Metal (Khold) (base16)'           ,
  'BreathLight (Gogh)'                     ,
  'Brewer (light) (terminal.sexy)'         ,
  'Brogrammer (base16)'                    ,
  'Brush Trees (base16)'                   ,
  'Brush Trees Dark (base16)'              ,
  'Builtin Solarized Light'                ,
  'Builtin Tango Light'                    ,
  'Catch Me If You Can (terminal.sexy)'    ,
  'Colorful Colors (terminal.sexy)'        ,
  'Cupertino (base16)'                     ,
  'Dark Violet (base16)'                   ,
  'DarkPastel (Gogh)'                      ,
  'Deafened (terminal.sexy)'               ,
  'DjangoRebornAgain'                      ,
  'Dotshare (terminal.sexy)'               ,
  'Earthsong (Gogh)'                       ,
  'Edge Light (base16)'                    ,
  'Ef-Melissa-Light'                       ,
  'Ef-Night'                               ,
  'Ef-Tritanopia-Light'                    ,
  'Ef-Winter'                              ,
  'Elementary (Gogh)'                      ,
  'Elementary'                             ,
  'Elio (Gogh)'                            ,
  'EspressoLibre (Gogh)'                   ,
  'Fahrenheit'                             ,
  'Floraverse'                             ,
  'Foxnightly (Gogh)'                      ,
  'Freya (Gogh)'                           ,
  'FrontendFunForrest (Gogh)'              ,
  'Galizur'                                ,
  'Geohot (Gogh)'                          ,
  'Github (base16)'                        ,
  'Github Light (Gogh)'                    ,
  'Google (light) (terminal.sexy)'         ,
  'Google Dark (Gogh)'                     ,
  'Gotham (Gogh)'                          ,
  'Grape'                                  ,
  'Grass (Gogh)'                           ,
  'Grass'                                  ,
  'Grayscale (dark) (terminal.sexy)'       ,
  'Gruvbox light, medium (base16)'         ,
  'Gruvbox light, soft (base16)'           ,
  'GruvboxDark'                            ,
  'HaX0R_BLUE'                             ,
  'Harper'                                 ,
  'Highway'                                ,
  'Homebrew Light (Gogh)'                  ,
  'Hurtado (Gogh)'                         ,
  'Ic Orange Ppl (Gogh)'                   ,
  'Icy Dark (base16)'                      ,
  'IdleToes (Gogh)'                        ,
  'Iiamblack (terminal.sexy)'              ,
  'Isotope (light) (terminal.sexy)'        ,
  'Jackie Brown (Gogh)'                    ,
  'Kimber (base16)'                        ,
  'Light White (terminal.sexy)'            ,
  'Liquid Carbon (Gogh)'                   ,
  'Lunaria Dark (Gogh)'                    ,
  'LunariaEclipse (Gogh)'                  ,
  'LunariaLight (Gogh)'                    ,
  'ManPage (Gogh)'                         ,
  'Mar (Gogh)'                             ,
  'Material Vivid (base16)'                ,
  'Material'                               ,
  'Modus-Operandi'                         ,
  'Modus-Operandi-Tritanopia'              ,
  'MonaLisa'                               ,
  'Mono Red (Gogh)'                        ,
  'Mono White (Gogh)'                      ,
  'Mono Yellow (Gogh)'                     ,
  'Neutron (Gogh)'                         ,
  'Nightlion V1 (Gogh)'                    ,
  'Nord Light (Gogh)'                      ,
  'Numix Darkest (terminal.sexy)'          ,
  'One Dark (Gogh)'                        ,
  'One Light (base16)'                     ,
  'PaperColor Dark (base16)'               ,
  'PaperColorLight (Gogh)'                 ,
  'Parker Brothers (terminal.sexy)'        ,
  'Pro'                                    ,
  'Rezza (terminal.sexy)'                  ,
  'Rosé Pine Dawn (Gogh)'                  ,
  'Sea Shells (Gogh)'                      ,
  'Seafoam Pastel (Gogh)'                  ,
  'Silk Light (base16)'                    ,
  'Solar Flare (base16)'                   ,
  'Solarized Light (Gogh)'                 ,
  'SolarizedDarcula (Gogh)'                ,
  'SolarizedLight (Gogh)'                  ,
  'Sublette'                               ,
  'Tartan (terminal.sexy)'                 ,
  'Terminal Basic'                         ,
  'ToyChest'                               ,
  'Treehouse'                              ,
  'Twilight (Gogh)'                        ,
  'UnderTheSea'                            ,
  'Unikitty Light (base16)'                ,
  'Urple (Gogh)'                           ,
  'Vag (Gogh)'                             ,
  'Vaughn (Gogh)'                          ,
  'VisiBone (terminal.sexy)'               ,
  'Warm Neon (Gogh)'                       ,
  'Whimsy'                                 ,
  'Windows 95 (base16)'                    ,
  'Windows High Contrast Light (base16)'   ,
  'Zenburn (base16)'                       ,
  'Zenburn'                                ,
  'alacritty'                              ,
  'carbonfox'                              ,
  'flexoki-dark'                           ,
  'gooey (Gogh)'                           ,
  'iceberg-light'                          ,
  'mono-green (Gogh)'                      ,
  'nord-light'                             ,
  'summercamp (base16)'                    ,
  'terafox'                                ,
  'thwump (terminal.sexy)'                 ,
  'zenbones_light'                         ,
  'IC_Orange_PPL'                          ,
  'Hardcore (base16)'                      ,
  'ForestBlue'                             ,
  'PaulMillr (Gogh)'                       ,
  'Atelier Savanna (base16)'               ,
  'Mikado (terminal.sexy)'                 ,
  'Laser'                                  ,
  'CGA'                                    ,
  'Hipster Green (Gogh)'                   ,
  'Liquid Carbon Transparent (Gogh)'       ,
  'Kasugano (terminal.sexy)'               ,
  'Eqie6 (terminal.sexy)'                  ,
  'Atelierlakeside (light) (terminal.sexy)',
  'Doom Peacock'                           ,
  'Modus-Operandi-Deuteranopia'            ,
  'Greenscreen (dark) (terminal.sexy)'     ,
  'Spacedust (Gogh)'                       ,
  'Fairy Floss Dark (Gogh)'                ,
  'deep'                                   ,
  'Gotham (terminal.sexy)'                 ,
  'Marrakesh (base16)'                     ,
  'Pali (Gogh)'                            ,
  'EverforestLight (Gogh)'                 ,
  'Neopolitan'                             ,
  'Atelier Forest (base16)'                ,
  'Atelier Cave (base16)'                  ,
  'Obsidian'                               ,
  'Tango (base16)'                         ,
  'Dehydration (Gogh)'                     ,
  'Apple Classic'                          ,
  'Default (dark) (terminal.sexy)'         ,
  'OneHalfLight'                           ,
  'Jup (Gogh)'                             ,
  'Purple Rain'                            ,
  'Ef-Elea-Light'                          ,
  'Glacier'                                ,
  'Apathy (base16)'                        ,
  'Twilight (light) (terminal.sexy)'       ,
}

return scheme_lst.mac

