
local scheme_lst = {}

scheme_lst.win = {}
scheme_lst.win.excld = {
  '3024 Day (Gogh)'                       ,
  'Atelier Plateau Light (base16)'        ,
  'Atelier Heath Light (base16)'          ,
  'Atelierseaside (light) (terminal.sexy)',
  'AyuLight (Gogh)'                       ,
  'CLRS'                                  ,
  'Canvased Pastel (terminal.sexy)'       ,
  'Ciapre (Gogh)'                         ,
  'Count Von Count (terminal.sexy)'       ,
  'CrayonPonyFish'                        ,
  'Ef-Frost'                              ,
  'Ef-Tritanopia-Light'                   ,
  'FrontendDelight (Gogh)'                ,
  'Github'                                ,
  'Google Light (base16)'                 ,
  'Google Light (Gogh)'                   ,
  'Greenscreen (dark) (terminal.sexy)'    ,
  'Gruvbox Light'                         ,
  'Harmonic16 Light (base16)'             ,
  'Homebrew (Gogh)'                       ,
  'Hybrid'                                ,
  'Icy Dark (base16)'                     ,
  'Lavandula (Gogh)'                      ,
  'Light White (terminal.sexy)'           ,
  'Lost Woods (terminal.sexy)'            ,
  'LunariaLight (Gogh)'                   ,
  'MaterialDark'                          ,
  'Mona Lisa (Gogh)'                      ,
  'Mono (terminal.sexy)'                  ,
  'Mono Green (Gogh)'                     ,
  'Monokai (light) (terminal.sexy)'       ,
  'Monokai Vivid'                         ,
  'Neutron'                               ,
  'OneHalfLight'                          ,
  'Pro (Gogh)'                            ,
  'Raycast_Light'                         ,
  'Sagelight (base16)'                    ,
  'Solarized Dark - Patched'              ,
  'Spiderman'                             ,
  'Tokyo Night Day'                       ,
  'TokyoNightLight (Gogh)'                ,
  'Unsifted Wheat (terminal.sexy)'        ,
  'nighty (Gogh)'                         ,
  'summercamp (base16)'                   ,
  'HemisuLight (Gogh)'                    ,
  'NightLion v1'                          ,
  'Edge Light (base16)'                   ,
  'Eldorado dark (terminal.sexy)'         ,
  'Belafonte Day'                         ,
  'Vacuous 2 (terminal.sexy)'             ,
  'Nighty (Gogh)'                         ,
  'RoséPine (Gogh)'                       ,
  'Dawn (terminal.sexy)'                  ,
  'Galaxy'                                ,
  'Wryan'                                 ,
  'Black Metal (Khold) (base16)'          ,
  'Black Metal (Mayhem) (base16)'         ,
  'PaperColorLight (Gogh)'                ,
  'CGA'                                   ,
  'Hardcore (base16)'                     ,
  'Grass'                                 ,
  'JWR dark (terminal.sexy)'              ,
  'Ubuntu'                                ,
  'HaX0R_GR33N'                           ,
  'Sundried'                              ,
  'Tangoesque (terminal.sexy)'            ,
  'MonokaiDark (Gogh)'                    ,
  'Atelierheath (dark) (terminal.sexy)'   ,
  'Kasugano (terminal.sexy)'              ,
  'Catch Me If You Can (terminal.sexy)'   ,
  'Man Page'                              ,
  'darkermatrix'                          ,
  'BlulocoZshLight (Gogh)'                ,
  'Jackie Brown'                          ,
  'Windows 95 Light (base16)'             ,
  'Vag (Gogh)'                            ,
  'GoogleLight (Gogh)'                    ,
  'Circus (base16)'                       ,
  'Violet Light'                          ,
  'Shapeshifter (dark) (terminal.sexy)'   ,
  'Freya (Gogh)'                          ,
  'mono-red (Gogh)'                       ,
}

scheme_lst.win.recommend = {}
scheme_lst.win.recommend.h = {
  'Snazzy (base16)'                       , -- < h
  'UltraViolent'                          ,
  'niji'                                  ,
  'Borland'                               ,
  'VibrantInk'                            ,
  'Synthwave (Gogh)'                      ,
  'tokyonight'                            ,
  'Everblush (Gogh)'                      ,
  'AyuMirage (Gogh)'                      ,
}
scheme_lst.win.recommend.m = {
  'Builtin Pastel Dark'                   ,
  'Dracula (Gogh)'                        ,
  'Ef-Trio-Dark'                          ,
  'Espresso Libre'                        ,
  'IdleToes (Gogh)'                       ,
  'Jellybeans'                            ,
  'Oxocarbon Dark (Gogh)'                 ,
  'PaperColorDark (Gogh)'                 ,
  'Purple People Eater (Gogh)'            ,
  'Red Alert'                             ,
  'Windows High Contrast (base16)'        ,
  'iTerm2 Smoooooth'                      ,
  'Purple Rain'                           ,
}

scheme_lst.mac = {}
scheme_lst.mac.excld = {
  'PaperColor Dark (base16)'              ,
}
scheme_lst.mac.recommend = {}
scheme_lst.mac.recommend.h = {
  'Framer (base16)'                       ,
}
scheme_lst.mac.recommend.m = {
}

return scheme_lst

