
-- mac

local scheme_lst = {}

scheme_lst.mac = {}
scheme_lst.mac.recommend = {}
scheme_lst.mac.recommend.h = {
  -- hh
  'Abernathy'                              ,
  'Chalk (base16)'                         ,
  'Dark Pastel (Gogh)'                     ,
  'Dracula (Gogh)'                         ,
  'FrontendGalaxy (Gogh)'                  ,
  'Galaxy'                                 ,
  'Grey-green'                             ,
  'IBM3270(HighContrast) (Gogh)'           ,
  'Ibm3270 (Gogh)'                         ,
  'Isotope (base16)'                       ,
  'Modus-Vivendi-Deuteranopia'             ,
  'Oxocarbon Dark (Gogh)'                  ,
  'Snazzy'                                 ,
  'Summer Pop (Gogh)'                      ,
  'SynthWave (Gogh)'                       ,
  'Synthwave (Gogh)'                       ,
  'TomorrowNightBlue (Gogh)'               ,
  'Wombat (Gogh)'                          ,
  'Wombat'                                 ,
  'cyberpunk'                              ,
  'ibm3270 (Gogh)'                         ,
  -- h
  'Aco (Gogh)'                             ,
  'Adventure'                              ,
  'Apple System Colors'                    ,
  'Argonaut (Gogh)'                        ,
  'Atom'                                   ,
  'Ayu Mirage'                             ,
  'Bamboo'                                 ,
  'Belge (terminal.sexy)'                  ,
  'Breeze'                                 ,
  'Chalk (Gogh)'                           ,
  'Chalk'                                  ,
  'DanQing (base16)'                       ,
  'Dark Pastel'                            ,
  'Desert (Gogh)'                          ,
  'Desert'                                 ,
  'DotGov'                                 ,
  'Dracula (Official)'                     ,
  'Dracula (base16)'                       ,
  'Dracula'                                ,
  'Dracula+'                               ,
  'Erebus (terminal.sexy)'                 ,
  'Fairyfloss'                             ,
  'Flat Remix (Gogh)'                      ,
  'Flatland'                               ,
  'Framer (base16)'                        ,
  'Gigavolt (base16)'                      ,
  'Helios (base16)'                        ,
  'Horizon Dark (base16)'                  ,
  'IR_Black'                               ,
  'Ibm 3270 (High Contrast) (Gogh)'        ,
  'Idle Toes (Gogh)'                       ,
  'Ir Black (Gogh)'                        ,
  'Jellybeans (Gogh)'                      ,
  'Kolorit'                                ,
  'Material Darker (base16)'               ,
  'MaterialDarker'                         ,
  'MaterialDesignColors'                   ,
  'Modus-Vivendi-Tinted'                   ,
  'Modus-Vivendi-Tritanopia'               ,
  'Monokai (base16)'                       ,
  'Monokai (dark) (terminal.sexy)'         ,
  'Monokai Pro (Gogh)'                     ,
  'Monokai Remastered'                     ,
  'MonokaiPro (Gogh)'                      ,
  'Neon (terminal.sexy)'                   ,
  'Nocturnal Winter'                       ,
  'Nucolors (terminal.sexy)'               ,
  'Obsidian (Gogh)'                        ,
  'OceanicMaterial'                        ,
  'OceanicNext (base16)'                   ,
  'Outrun Dark (base16)'                   ,
  'Panda (Gogh)'                           ,
  'Poimandres Storm'                       ,
  'Poimandres'                             ,
  'Predawn (Gogh)'                         ,
  'Raycast_Dark'                           ,
  'Rebecca (base16)'                       ,
  'Snazzy (Gogh)'                          ,
  'Snazzy (base16)'                        ,
  'Sonokai (Gogh)'                         ,
  'Splurge (terminal.sexy)'                ,
  'Subliminal'                             ,
  'Symfonic'                               ,
  'Symphonic (Gogh)'                       ,
  'Tokyo Night'                            ,
  'TokyoNight (Gogh)'                      ,
  'Tomorrow Night Blue (Gogh)'             ,
  'arcoiris'                               ,
  'astel White (terminal.sexy)'            ,
  'astromouse (terminal.sexy)'             ,
  'ayu'                                    ,
  'catppuccin-mocha'                       ,
  'farmhouse-dark'                         ,
  'hardhacker'                             ,
  'idleToes'                               ,
  'jmbi (terminal.sexy)'                   ,
  'niji'                                   ,
  'synthwave'                              ,
  'tokyonight_moon'                        ,
  'tokyonight_storm'                       ,
}
scheme_lst.mac.recommend.m = {
}
scheme_lst.mac.check = {
  'Aardvark Blue'                          ,
  'Adventure Time (Gogh)'                  ,
  'Afterglow (Gogh)'                       ,
  'Andromeda'                              ,
  'Argonaut'                               ,
  'Arthur'                                 ,
  'Atom (Gogh)'                            ,
  'Aura (Gogh)'                            ,
  'Ayu Mirage (Gogh)'                      ,
  'AyuMirage (Gogh)'                       ,
  'Bamboo Multiplex'                       ,
  'Banana Blueberry'                       ,
  'Bim (Gogh)'                             ,
  'Birds Of Paradise (Gogh)'               ,
  'BirdsOfParadise'                        ,
  'BlueDolphin'                            ,
  'BlulocoDark'                            ,
  'Borland'                                ,
  'Breeze (Gogh)'                          ,
  'Bright (base16)'                        ,
  'Bright Lights'                          ,
  'Brogrammer (Gogh)'                      ,
  'Builtin Dark'                           ,
  'Builtin Pastel Dark'                    ,
  'Cai (Gogh)'                             ,
  'Catppuccin Frappe'                      ,
  'Catppuccin Frappé (Gogh)'               ,
  'Catppuccin Macchiato (Gogh)'            ,
  'Catppuccin Macchiato'                   ,
  'Catppuccin Mocha (Gogh)'                ,
  'Catppuccin Mocha'                       ,
  'Chalk (dark) (terminal.sexy)'           ,
  'Chalkboard'                             ,
  'ChallengerDeep'                         ,
  'Chester'                                ,
  'Classic Dark (base16)'                  ,
  'Cobalt 2 (Gogh)'                        ,
  'Cobalt2'                                ,
  'Dark+'                                  ,
  'Darkside (Gogh)'                        ,
  'Darkside'                               ,
  'DeHydration (Gogh)'                     ,
  'Default Dark (base16)'                  ,
  'DimmedMonokai'                          ,
  'Dissonance (Gogh)'                      ,
  'Ef-Autumn'                              ,
  'Ef-Bio'                                 ,
  'Ef-Cherie'                              ,
  'Ef-Deuteranopia-Dark'                   ,
  'Ef-Duo-Dark'                            ,
  'Ef-Elea-Dark'                           ,
  'Ef-Maris-Dark'                          ,
  'Ef-Melissa-Dark'                        ,
  'Ef-Rosa'                                ,
  'Ef-Trio-Dark'                           ,
  'Ef-Tritanopia-Dark'                     ,
  'Eighties (base16)'                      ,
  'Eighties (dark) (terminal.sexy)'        ,
  'Elic (Gogh)'                            ,
  'Equilibrium Dark (base16)'              ,
  'Espresso (Gogh)'                        ,
  'Espresso (base16)'                      ,
  'Espresso'                               ,
  'Everblush (Gogh)'                       ,
  'Everblush'                              ,
  'Everforest Dark (Gogh)'                 ,
  'FairyFlossDark (Gogh)'                  ,
  'Flat (base16)'                          ,
  'FlatRemix (Gogh)'                       ,
  'Flatland (Gogh)'                        ,
  'Frontend Galaxy (Gogh)'                 ,
  'GJM (terminal.sexy)'                    ,
  'GeoHot (Gogh)'                          ,
  'Gogh (Gogh)'                            ,
  'Google (dark) (terminal.sexy)'          ,
  'GoogleDark (Gogh)'                      ,
  'Grandshell (terminal.sexy)'             ,
  'Grape (Gogh)'                           ,
  'GruvboxDarkHard'                        ,
  'Harmonic16 Dark (base16)'               ,
  'Hemisu Dark (Gogh)'                     ,
  'Hivacruz'                               ,
  'Hopscotch.256'                          ,
  'Horizon Dark (Gogh)'                    ,
  'HorizonDark (Gogh)'                     ,
  'Humanoid dark (base16)'                 ,
  'Hurtado'                                ,
  'Hybrid'                                 ,
  'ICGreenPPL (Gogh)'                      ,
  'IrBlack (Gogh)'                         ,
  'Isotope (dark) (terminal.sexy)'         ,
  'Japanesque'                             ,
  'Jellybeans'                             ,
  'Kibble (Gogh)'                          ,
  'Kibble'                                 ,
  'Kokuban (Gogh)'                         ,
  'Konsolas'                               ,
  'Lab Fox'                                ,
  'LiquidCarbon'                           ,
  'LiquidCarbonTransparentInverse'         ,
  'London Tube (base16)'                   ,
  'Londontube (dark) (terminal.sexy)'      ,
  'Materia (base16)'                       ,
  'Material (Gogh)'                        ,
  'Material (base16)'                      ,
  'Mathias (Gogh)'                         ,
  'Mathias'                                ,
  'Mellow Purple (base16)'                 ,
  'Mikazuki (terminal.sexy)'               ,
  'Misterioso (Gogh)'                      ,
  'Mocha (base16)'                         ,
  'Modus-Vivendi'                          ,
  'Molokai (Gogh)'                         ,
  'Molokai'                                ,
  'Monokai (terminal.sexy)'                ,
  'Monokai Dark (Gogh)'                    ,
  'Monokai Pro Ristretto (Gogh)'           ,
  'Monokai Soda'                           ,
  'Monokai Vivid'                          ,
  'MonokaiDark (Gogh)'                     ,
  'MonokaiProRistretto (Gogh)'             ,
  'Moonfly (Gogh)'                         ,
  'Morada (Gogh)'                          ,
  'Neon Night (Gogh)'                      ,
  'Night Owl (Gogh)'                       ,
  'NightLion v2'                           ,
  'NightOwl (Gogh)'                        ,
  'Nord (Gogh)'                            ,
  'Ocean (dark) (terminal.sexy)'           ,
  'Ocean'                                  ,
  'OneHalfBlack (Gogh)'                    ,
  'OneHalfDark'                            ,
  'Orangish (terminal.sexy)'               ,
  'PaleNightHC'                            ,
  'Palenight (Gogh)'                       ,
  'Pandora'                                ,
  'PaperColorDark (Gogh)'                  ,
  'Pastel White (terminal.sexy)'           ,
  'Paul Millr (Gogh)'                      ,
  'Pencil Dark (Gogh)'                     ,
  'Peppermint (Gogh)'                      ,
  'Pixiefloss (Gogh)'                      ,
  'Pnevma (Gogh)'                          ,
  'Pnevma'                                 ,
  'Popping and Locking'                    ,
  'Pro (Gogh)'                             ,
  'Purple People Eater (Gogh)'             ,
  'PurplePeopleEater (Gogh)'               ,
  'Purpledream (base16)'                   ,
  'Railscasts (base16)'                    ,
  'Railscasts (dark) (terminal.sexy)'      ,
  'Rapture'                                ,
  'Raycast_Light'                          ,
  'Red Alert (Gogh)'                       ,
  'Red Sands (Gogh)'                       ,
  'Red Sands'                              ,
  'RedAlert (Gogh)'                        ,
  'Rosé Pine Moon (Gogh)'                  ,
  'Rosé Pine Moon (base16)'                ,
  'RoséPine (Gogh)'                        ,
  'RoséPineMoon (Gogh)'                    ,
  'SeafoamPastel (Gogh)'                   ,
  'Seti (Gogh)'                            ,
  'Seti UI (base16)'                       ,
  'Seti'                                   ,
  'Silk Dark (base16)'                     ,
  'Simple Rainbow (terminal.sexy)'         ,
  'Solarized Darcula (Gogh)'               ,
  'Solarized Dark Higher Contrast (Gogh)'  ,
  'SpaceGray Eighties Dull'                ,
  'Spacegray Eighties (Gogh)'              ,
  'Spacegray Eighties Dull (Gogh)'         ,
  'Spiderman'                              ,
  'Srcery (Gogh)'                          ,
  'Sweet Eliverlara (Gogh)'                ,
  'Sweet Terminal (Gogh)'                  ,
  'SweetTerminal (Gogh)'                   ,
  'Synth Midnight Terminal Dark (base16)'  ,
  'SynthwaveAlpha (Gogh)'                  ,
  'SynthwaveAlpha'                         ,
  'Teerb (Gogh)'                           ,
  'Teerb'                                  ,
  'Tender (Gogh)'                          ,
  'Thayer Bright (Gogh)'                   ,
  'Thayer Bright'                          ,
  'ThayerBright (Gogh)'                    ,
  'Tinacious Design (Dark)'                ,
  'Tokyo Night (Gogh)'                     ,
  'Tokyo Night Moon'                       ,
  'Tokyo Night Storm (Gogh)'               ,
  'Tokyo Night Storm'                      ,
  'TokyoNightStorm (Gogh)'                 ,
  'Tomorrow Night (Gogh)'                  ,
  'Tomorrow Night Blue'                    ,
  'Tomorrow Night Bright (Gogh)'           ,
  'Tomorrow Night Bright'                  ,
  'Tomorrow Night'                         ,
  'TomorrowNightBright (Gogh)'             ,
  'TomorrowNightEighties (Gogh)'           ,
  'UltraDark'                              ,
  'Unikitty Dark (base16)'                 ,
  'VSCodeDark+ (Gogh)'                     ,
  'Vaughn'                                 ,
  'Vibrant Ink (Gogh)'                     ,
  'VibrantInk'                             ,
  'Vs Code Dark+ (Gogh)'                   ,
  'Website (Gogh)'                         ,
  'Wild Cherry (Gogh)'                     ,
  'WildCherry'                             ,
  'Windows 10 (base16)'                    ,
  'Windows NT (base16)'                    ,
  'catppuccin-frappe'                      ,
  'catppuccin-macchiato'                   ,
  'darkmoss (base16)'                      ,
  'duckbones'                              ,
  'duskfox'                                ,
  'gotham (Gogh)'                          ,
  'iTerm2 Dark Background'                 ,
  'iTerm2 Smoooooth'                       ,
  'iTerm2 Tango Dark'                      ,
  'iceberg-dark'                           ,
  'ight Owl (Gogh)'                        ,
  'lovelace'                               ,
  'midnight-in-mojave'                     ,
  'neon-night (Gogh)'                      ,
  'nightfox'                               ,
  'nord'                                   ,
  'nordfox'                                ,
  'palenight (Gogh)'                       ,
  'rebecca'                                ,
  'rose-pine'                              ,
  'rose-pine-moon'                         ,
  'seoulbones_dark'                        ,
  'shades-of-purple'                       ,
  'summer-pop (Gogh)'                      ,
  'synthwave-everything'                   ,
  'tender (base16)'                        ,
  'theme2 (terminal.sexy)'                 ,
  'tokyonight-storm'                       ,
  'tokyonight_night'                       ,
}
scheme_lst.mac.excld = {
  -- 
  -- phase 03
  -- 
  'Aci (Gogh)'                             ,
  'Fairy Floss (Gogh)'                     ,
  'Hopscotch (base16)'                     ,
  'Neopolitan (Gogh)'                      ,
  'Operator Mono Dark'                     ,
  'Pulp (terminal.sexy)'                   ,
  'Spring (Gogh)'                          ,
  'kanagawabones'                          ,
  'purplepeter'                            ,
  'tokyonight'                             ,
  -- 
  -- phase 02
  -- 
  '3024 (base16)'                          ,
  'Arthur (Gogh)'                          ,
  'Blazer'                                 ,
  'BlueBerryPie'                           ,
  'Breath Silverfox (Gogh)'                ,
  'Brewer (base16)'                        ,
  'Brogrammer'                             ,
  'Builtin Tango Dark'                     ,
  'Calamity'                               ,
  'Campbell (Gogh)'                        ,
  'Chalkboard (Gogh)'                      ,
  'Circus (base16)'                        ,
  'Clone Of Ubuntu (Gogh)'                 ,
  'Color Star (terminal.sexy)'             ,
  'Colors (base16)'                        ,
  'Digerati (terminal.sexy)'               ,
  'Dimmed Monokai (Gogh)'                  ,
  'DjangoSmooth'                           ,
  'DoomOne'                                ,
  'Edge Dark (base16)'                     ,
  'Espresso Libre'                         ,
  'EverforestDark (Gogh)'                  ,
  'FrontEndDelight'                        ,
  'Frontend Delight (Gogh)'                ,
  'Gruvbox Dark (Gogh)'                    ,
  'Gruvbox Material (Gogh)'                ,
  'Gruvbox dark, hard (base16)'            ,
  'Guezwhoz'                               ,
  'Heetch Dark (base16)'                   ,
  'Homebrew Ocean (Gogh)'                  ,
  'IC_Green_PPL'                           ,
  'Kanagawa (Gogh)'                        ,
  'Later This Evening (Gogh)'              ,
  'MaterialDark'                           ,
  'Miu (Gogh)'                             ,
  'Mocha (dark) (terminal.sexy)'           ,
  'Mono Theme (terminal.sexy)'             ,
  'Monokai Soda (Gogh)'                    ,
  'Muse (terminal.sexy)'                   ,
  'NightLion v1'                           ,
  'Nightfly (Gogh)'                        ,
  'NightlionV2 (Gogh)'                     ,
  'Nighty (Gogh)'                          ,
  'Nord (base16)'                          ,
  'Ocean (base16)'                         ,
  'OceanDark (Gogh)'                       ,
  'One Half Black (Gogh)'                  ,
  'OneDark (base16)'                       ,
  'Overnight Slumber'                      ,
  'Papercolor Dark (Gogh)'                 ,
  'PaulMillr'                              ,
  'Peppermint'                             ,
  'Phrak1 (terminal.sexy)'                 ,
  'Pop (base16)'                           ,
  'Porple (base16)'                        ,
  'PowerShell (Gogh)'                      ,
  'Qualia (base16)'                        ,
  'RedSands (Gogh)'                        ,
  'Shades of Purple (base16)'              ,
  'Shapeshifter (dark) (terminal.sexy)'    ,
  'Smyck'                                  ,
  'SpaceGray Eighties'                     ,
  'Summerfruit Dark (base16)'              ,
  'Tomorrow Night Eighties'                ,
  'Twilight (dark) (terminal.sexy)'        ,
  'Visibone Alt. 2 (terminal.sexy)'        ,
  'iTerm2 Default'                         ,
  'iTerm2 Pastel Dark Background'          ,
  'nighty (Gogh)'                          ,
  'pinky (base16)'                         ,
  'sweet-eliverlara (Gogh)'                ,
  'zenbones_dark'                          ,
  'zenburned'                              ,
  'zenwritten_dark'                        ,
  -- 
  -- phase 01
  -- 
  '3024 (dark) (terminal.sexy)'            ,
  '3024 (light) (terminal.sexy)'           ,
  '3024 Day (Gogh)'                        ,
  '3024 Day'                               ,
  '3024 Night (Gogh)'                      ,
  '3024 Night'                             ,
  '3024Day (Gogh)'                         ,
  '3024Night (Gogh)'                       ,
  'AdventureTime'                          ,
  'Afterglow'                              ,
  'Alabaster'                              ,
  'Alien Blood (Gogh)'                     ,
  'AlienBlood'                             ,
  'Apathy (base16)'                        ,
  'Apple Classic'                          ,
  'Apprentice (Gogh)'                      ,
  'Apprentice (base16)'                    ,
  'Ashes (base16)'                         ,
  'Ashes (dark) (terminal.sexy)'           ,
  'Ashes (light) (terminal.sexy)'          ,
  'Atelier Cave (base16)'                  ,
  'Atelier Cave Light (base16)'            ,
  'Atelier Dune (base16)'                  ,
  'Atelier Dune Light (base16)'            ,
  'Atelier Estuary (base16)'               ,
  'Atelier Estuary Light (base16)'         ,
  'Atelier Forest (base16)'                ,
  'Atelier Forest Light (base16)'          ,
  'Atelier Heath (base16)'                 ,
  'Atelier Heath Light (base16)'           ,
  'Atelier Lakeside (base16)'              ,
  'Atelier Lakeside Light (base16)'        ,
  'Atelier Plateau (base16)'               ,
  'Atelier Plateau Light (base16)'         ,
  'Atelier Savanna (base16)'               ,
  'Atelier Savanna Light (base16)'         ,
  'Atelier Seaside (base16)'               ,
  'Atelier Seaside Light (base16)'         ,
  'Atelier Sulphurpool (base16)'           ,
  'Atelier Sulphurpool Light (base16)'     ,
  'AtelierSulphurpool'                     ,
  'Atelierdune (dark) (terminal.sexy)'     ,
  'Atelierdune (light) (terminal.sexy)'    ,
  'Atelierforest (dark) (terminal.sexy)'   ,
  'Atelierforest (light) (terminal.sexy)'  ,
  'Atelierheath (dark) (terminal.sexy)'    ,
  'Atelierheath (light) (terminal.sexy)'   ,
  'Atelierlakeside (dark) (terminal.sexy)' ,
  'Atelierlakeside (light) (terminal.sexy)',
  'Atelierseaside (dark) (terminal.sexy)'  ,
  'Atelierseaside (light) (terminal.sexy)' ,
  'Atlas (base16)'                         ,
  'AtomOneLight'                           ,
  'Aurora'                                 ,
  'Ayu Dark (Gogh)'                        ,
  'Ayu Light (Gogh)'                       ,
  'AyuDark (Gogh)'                         ,
  'AyuLight (Gogh)'                        ,
  'Azu (Gogh)'                             ,
  'Bamboo Light'                           ,
  'Batman'                                 ,
  'Belafonte Day (Gogh)'                   ,
  'Belafonte Day'                          ,
  'Belafonte Night (Gogh)'                 ,
  'Belafonte Night'                        ,
  'BelafonteDay (Gogh)'                    ,
  'BelafonteNight (Gogh)'                  ,
  'Bespin (base16)'                        ,
  'Bespin (dark) (terminal.sexy)'          ,
  'Bespin (light) (terminal.sexy)'         ,
  'Bitmute (terminal.sexy)'                ,
  'Black Metal (Bathory) (base16)'         ,
  'Black Metal (Burzum) (base16)'          ,
  'Black Metal (Dark Funeral) (base16)'    ,
  'Black Metal (Gorgoroth) (base16)'       ,
  'Black Metal (Immortal) (base16)'        ,
  'Black Metal (Khold) (base16)'           ,
  'Black Metal (Marduk) (base16)'          ,
  'Black Metal (Mayhem) (base16)'          ,
  'Black Metal (Nile) (base16)'            ,
  'Black Metal (Venom) (base16)'           ,
  'Black Metal (base16)'                   ,
  'Blazer (Gogh)'                          ,
  'Bleh-1 (terminal.sexy)'                 ,
  'Blue Matrix'                            ,
  'Bluloco Light (Gogh)'                   ,
  'Bluloco Zsh Light (Gogh)'               ,
  'BlulocoLight (Gogh)'                    ,
  'BlulocoLight'                           ,
  'BlulocoZshLight (Gogh)'                 ,
  'Borland (Gogh)'                         ,
  'Breath (Gogh)'                          ,
  'Breath Darker (Gogh)'                   ,
  'Breath Light (Gogh)'                    ,
  'BreathLight (Gogh)'                     ,
  'BreathSilverfox (Gogh)'                 ,
  'Brewer (dark) (terminal.sexy)'          ,
  'Brewer (light) (terminal.sexy)'         ,
  'Broadcast (Gogh)'                       ,
  'Broadcast'                              ,
  'Brogrammer (base16)'                    ,
  'Brush Trees (base16)'                   ,
  'Brush Trees Dark (base16)'              ,
  'Builtin Light'                          ,
  'Builtin Solarized Dark'                 ,
  'Builtin Solarized Light'                ,
  'Builtin Tango Light'                    ,
  'C64 (Gogh)'                             ,
  'C64'                                    ,
  'CGA'                                    ,
  'CLRS'                                   ,
  'Canvased Pastel (terminal.sexy)'        ,
  'Catch Me If You Can (terminal.sexy)'    ,
  'Catppuccin Latte (Gogh)'                ,
  'Catppuccin Latte'                       ,
  'Chalk (light) (terminal.sexy)'          ,
  'Chameleon (Gogh)'                       ,
  'Ciapre (Gogh)'                          ,
  'Ciapre'                                 ,
  'City Streets (terminal.sexy)'           ,
  'Classic Light (base16)'                 ,
  'CloneofUbuntu (Gogh)'                   ,
  'Cloud (terminal.sexy)'                  ,
  'Clrs (Gogh)'                            ,
  'Cobalt Neon (Gogh)'                     ,
  'Cobalt Neon'                            ,
  'CobaltNeon (Gogh)'                      ,
  'Codeschool (base16)'                    ,
  'Codeschool (dark) (terminal.sexy)'      ,
  'Codeschool (light) (terminal.sexy)'     ,
  'Colorcli (Gogh)'                        ,
  'Colorful Colors (terminal.sexy)'        ,
  'Count Von Count (terminal.sexy)'        ,
  'Crayon Pony Fish (Gogh)'                ,
  'CrayonPonyFish'                         ,
  'Cupcake (base16)'                       ,
  'Cupertino (base16)'                     ,
  'Cyberdyne'                              ,
  'DWM rob (terminal.sexy)'                ,
  'DanQing Light (base16)'                 ,
  'Darcula (base16)'                       ,
  'Dark Ocean (terminal.sexy)'             ,
  'Dark Violet (base16)'                   ,
  'DarkPastel (Gogh)'                      ,
  'Darktooth (base16)'                     ,
  'Dawn (terminal.sexy)'                   ,
  'Deafened (terminal.sexy)'               ,
  'Decaf (base16)'                         ,
  'Default (dark) (terminal.sexy)'         ,
  'Default (light) (terminal.sexy)'        ,
  'Default Light (base16)'                 ,
  'Dehydration (Gogh)'                     ,
  'Derp (terminal.sexy)'                   ,
  'Django'                                 ,
  'DjangoRebornAgain'                      ,
  'Doom Peacock'                           ,
  'Dotshare (terminal.sexy)'               ,
  'Duotone Dark'                           ,
  'ENCOM'                                  ,
  'Earthsong (Gogh)'                       ,
  'Earthsong'                              ,
  'Edge Light (base16)'                    ,
  'Ef-Arbutus'                             ,
  'Ef-Cyprus'                              ,
  'Ef-Dark'                                ,
  'Ef-Day'                                 ,
  'Ef-Deuteranopia-Light'                  ,
  'Ef-Duo-Light'                           ,
  'Ef-Elea-Light'                          ,
  'Ef-Frost'                               ,
  'Ef-Kassio'                              ,
  'Ef-Light'                               ,
  'Ef-Maris-Light'                         ,
  'Ef-Melissa-Light'                       ,
  'Ef-Night'                               ,
  'Ef-Spring'                              ,
  'Ef-Summer'                              ,
  'Ef-Symbiosis'                           ,
  'Ef-Trio-Light'                          ,
  'Ef-Tritanopia-Light'                    ,
  'Ef-Winter'                              ,
  'Eighties (light) (terminal.sexy)'       ,
  'Eldorado dark (terminal.sexy)'          ,
  'Elemental (Gogh)'                       ,
  'Elemental'                              ,
  'Elementary (Gogh)'                      ,
  'Elementary'                             ,
  'Elio (Gogh)'                            ,
  'Embers (base16)'                        ,
  'Embers (dark) (terminal.sexy)'          ,
  'Embers (light) (terminal.sexy)'         ,
  'Epiphany (terminal.sexy)'               ,
  'Eqie6 (terminal.sexy)'                  ,
  'Equilibrium Gray Dark (base16)'         ,
  'Equilibrium Gray Light (base16)'        ,
  'Equilibrium Light (base16)'             ,
  'Espresso Libre (Gogh)'                  ,
  'EspressoLibre (Gogh)'                   ,
  'Euphrasia (terminal.sexy)'              ,
  'Eva (base16)'                           ,
  'Eva Dim (base16)'                       ,
  'Everforest Light (Gogh)'                ,
  'EverforestLight (Gogh)'                 ,
  'Fahrenheit'                             ,
  'Fairy Floss Dark (Gogh)'                ,
  'FairyFloss (Gogh)'                      ,
  'FarSide (terminal.sexy)'                ,
  'Fideloper'                              ,
  'Firefly Traditional'                    ,
  'FirefoxDev'                             ,
  'Firewatch'                              ,
  'FishTank'                               ,
  'Fishbone (terminal.sexy)'               ,
  'Fishtank (Gogh)'                        ,
  'Flat (Gogh)'                            ,
  'Flat'                                   ,
  'Floraverse'                             ,
  'ForestBlue'                             ,
  'Foxnightly (Gogh)'                      ,
  'Framer'                                 ,
  'Freya (Gogh)'                           ,
  'Frontend Fun Forrest (Gogh)'            ,
  'FrontendDelight (Gogh)'                 ,
  'FrontendFunForrest (Gogh)'              ,
  'Fruit Soda (base16)'                    ,
  'FunForrest'                             ,
  'Galizur'                                ,
  'Geohot (Gogh)'                          ,
  'GitHub Dark'                            ,
  'Github (Gogh)'                          ,
  'Github (base16)'                        ,
  'Github Dark (Gogh)'                     ,
  'Github Light (Gogh)'                    ,
  'Github'                                 ,
  'Glacier'                                ,
  'Gnometerm (terminal.sexy)'              ,
  'Gooey (Gogh)'                           ,
  'Google (light) (terminal.sexy)'         ,
  'Google Dark (Gogh)'                     ,
  'Google Dark (base16)'                   ,
  'Google Light (Gogh)'                    ,
  'Google Light (base16)'                  ,
  'GoogleLight (Gogh)'                     ,
  'Gotham (Gogh)'                          ,
  'Gotham (terminal.sexy)'                 ,
  'Grape'                                  ,
  'Grass (Gogh)'                           ,
  'Grass'                                  ,
  'Grayscale (dark) (terminal.sexy)'       ,
  'Grayscale (light) (terminal.sexy)'      ,
  'Grayscale Dark (base16)'                ,
  'Grayscale Light (base16)'               ,
  'Green Screen (base16)'                  ,
  'Greenscreen (dark) (terminal.sexy)'     ,
  'Greenscreen (light) (terminal.sexy)'    ,
  'Gruber (base16)'                        ,
  'Gruvbox (Gogh)'                         ,
  'Gruvbox Light'                          ,
  'Gruvbox dark, medium (base16)'          ,
  'Gruvbox dark, pale (base16)'            ,
  'Gruvbox dark, soft (base16)'            ,
  'Gruvbox light, hard (base16)'           ,
  'Gruvbox light, medium (base16)'         ,
  'Gruvbox light, soft (base16)'           ,
  'GruvboxDark'                            ,
  'GruvboxLight'                           ,
  'HaX0R_BLUE'                             ,
  'HaX0R_GR33N'                            ,
  'HaX0R_R3D'                              ,
  'Hacktober'                              ,
  'Hardcore (Gogh)'                        ,
  'Hardcore (base16)'                      ,
  'Hardcore'                               ,
  'Harmonic16 Light (base16)'              ,
  'Harper (Gogh)'                          ,
  'Harper'                                 ,
  'Heetch Light (base16)'                  ,
  'Hemisu Light (Gogh)'                    ,
  'HemisuDark (Gogh)'                      ,
  'HemisuLight (Gogh)'                     ,
  'Highway (Gogh)'                         ,
  'Highway'                                ,
  'Hipster Green (Gogh)'                   ,
  'Hipster Green'                          ,
  'HipsterGreen (Gogh)'                    ,
  'Homebrew (Gogh)'                        ,
  'Homebrew Light (Gogh)'                  ,
  'Homebrew'                               ,
  'Hopscotch'                              ,
  'Horizon Bright (Gogh)'                  ,
  'Horizon Light (base16)'                 ,
  'HorizonBright (Gogh)'                   ,
  'Humanoid light (base16)'                ,
  'Hurtado (Gogh)'                         ,
  'Hybrid (Gogh)'                          ,
  'Hybrid (terminal.sexy)'                 ,
  'ICOrangePPL (Gogh)'                     ,
  'IC_Orange_PPL'                          ,
  'IR Black (base16)'                      ,
  'Ic Green Ppl (Gogh)'                    ,
  'Ic Orange Ppl (Gogh)'                   ,
  'Icy Dark (base16)'                      ,
  'IdleToes (Gogh)'                        ,
  'Iiamblack (terminal.sexy)'              ,
  'Insignificato (terminal.sexy)'          ,
  'Invisibone (terminal.sexy)'             ,
  'Isotope (light) (terminal.sexy)'        ,
  'Ivory Dark (terminal.sexy)'             ,
  'Ivory Light (terminal.sexy)'            ,
  'JWR dark (terminal.sexy)'               ,
  'Jackie Brown (Gogh)'                    ,
  'Jackie Brown'                           ,
  'JackieBrown (Gogh)'                     ,
  'Japanesque (Gogh)'                      ,
  'Jason Wryan (terminal.sexy)'            ,
  'JetBrains Darcula'                      ,
  'Jup (Gogh)'                             ,
  'Kasugano (terminal.sexy)'               ,
  'Kimber (base16)'                        ,
  'Laser'                                  ,
  'Laserwave (Gogh)'                       ,
  'Later This Evening'                     ,
  'LaterThisEvening (Gogh)'                ,
  'Lavandula (Gogh)'                       ,
  'Lavandula'                              ,
  'Light White (terminal.sexy)'            ,
  'Liquid Carbon (Gogh)'                   ,
  'Liquid Carbon Transparent (Gogh)'       ,
  'LiquidCarbonTransparent'                ,
  'Londontube (light) (terminal.sexy)'     ,
  'Lost Woods (terminal.sexy)'             ,
  'Low Contrast (terminal.sexy)'           ,
  'Lumifoo (terminal.sexy)'                ,
  'Lunaria Dark (Gogh)'                    ,
  'Lunaria Eclipse (Gogh)'                 ,
  'Lunaria Light (Gogh)'                   ,
  'LunariaDark (Gogh)'                     ,
  'LunariaEclipse (Gogh)'                  ,
  'LunariaLight (Gogh)'                    ,
  'Macintosh (base16)'                     ,
  'Maia (Gogh)'                            ,
  'Man Page (Gogh)'                        ,
  'Man Page'                               ,
  'ManPage (Gogh)'                         ,
  'Mar (Gogh)'                             ,
  'Mariana'                                ,
  'Marrakesh (base16)'                     ,
  'Marrakesh (dark) (terminal.sexy)'       ,
  'Marrakesh (light) (terminal.sexy)'      ,
  'Mashup Colors (terminal.sexy)'          ,
  'Material (terminal.sexy)'               ,
  'Material Lighter (base16)'              ,
  'Material Palenight (base16)'            ,
  'Material Vivid (base16)'                ,
  'Material'                               ,
  'MaterialOcean'                          ,
  'Matrix (terminal.sexy)'                 ,
  'Medallion (Gogh)'                       ,
  'Medallion'                              ,
  'Mexico Light (base16)'                  ,
  'Mikado (terminal.sexy)'                 ,
  'Mirage'                                 ,
  'Misterioso'                             ,
  'Mocha (light) (terminal.sexy)'          ,
  'Modus-Operandi'                         ,
  'Modus-Operandi-Deuteranopia'            ,
  'Modus-Operandi-Tinted'                  ,
  'Modus-Operandi-Tritanopia'              ,
  'Mona Lisa (Gogh)'                       ,
  'MonaLisa'                               ,
  'Mono (terminal.sexy)'                   ,
  'Mono Amber (Gogh)'                      ,
  'Mono Cyan (Gogh)'                       ,
  'Mono Green (Gogh)'                      ,
  'Mono Red (Gogh)'                        ,
  'Mono White (Gogh)'                      ,
  'Mono Yellow (Gogh)'                     ,
  'Monokai (light) (terminal.sexy)'        ,
  'MonokaiSoda (Gogh)'                     ,
  'Mostly Bright (terminal.sexy)'          ,
  'N0Tch2K (Gogh)'                         ,
  'N0tch2k'                                ,
  'Nancy (terminal.sexy)'                  ,
  'Nature Suede (terminal.sexy)'           ,
  'Navy and Ivory (terminal.sexy)'         ,
  'Nebula (base16)'                        ,
  'Neon'                                   ,
  'Neopolitan'                             ,
  'Nep (Gogh)'                             ,
  'Neutron (Gogh)'                         ,
  'Neutron'                                ,
  'Night Owlish Light'                     ,
  'Nightlion V1 (Gogh)'                    ,
  'Nightlion V2 (Gogh)'                    ,
  'NightlionV1 (Gogh)'                     ,
  'Nord Light (Gogh)'                      ,
  'NordLight (Gogh)'                       ,
  'Nova (base16)'                          ,
  'Novel (Gogh)'                           ,
  'Novel'                                  ,
  'Nudge (terminal.sexy)'                  ,
  'Numix Darkest (terminal.sexy)'          ,
  'Obsidian'                               ,
  'Ocean (light) (terminal.sexy)'          ,
  'Ocean Dark (Gogh)'                      ,
  'Oceanic Next (Gogh)'                    ,
  'Oceanic-Next'                           ,
  'OceanicNext (Gogh)'                     ,
  'Ollie (Gogh)'                           ,
  'Ollie'                                  ,
  'Omni (Gogh)'                            ,
  'One Dark (Gogh)'                        ,
  'One Light (Gogh)'                       ,
  'One Light (base16)'                     ,
  'OneDark (Gogh)'                         ,
  'OneHalfLight'                           ,
  'OneLight (Gogh)'                        ,
  'Pali (Gogh)'                            ,
  'Panels (terminal.sexy)'                 ,
  'PaperColor Dark (base16)'               ,
  'PaperColor Light (base16)'              ,
  'PaperColorLight (Gogh)'                 ,
  'Papercolor Light (Gogh)'                ,
  'Paraiso (base16)'                       ,
  'Paraiso (dark) (terminal.sexy)'         ,
  'Paraiso (light) (terminal.sexy)'        ,
  'Paraiso Dark (Gogh)'                    ,
  'Paraiso Dark'                           ,
  'ParaisoDark (Gogh)'                     ,
  'Parker Brothers (terminal.sexy)'        ,
  'Pasque (base16)'                        ,
  'PaulMillr (Gogh)'                       ,
  'Pencil Light (Gogh)'                    ,
  'PencilDark'                             ,
  'PencilLight'                            ,
  'PhD (base16)'                           ,
  'Piatto Light'                           ,
  'Pico (base16)'                          ,
  'Powershell (Gogh)'                      ,
  'Pretty and Pastel (terminal.sexy)'      ,
  'Pro Light'                              ,
  'Pro'                                    ,
  'Purple Rain'                            ,
  'Railscasts (light) (terminal.sexy)'     ,
  'Rasi (terminal.sexy)'                   ,
  'Red Alert'                              ,
  'Red Phoenix (terminal.sexy)'            ,
  'Red Planet'                             ,
  'Relaxed (Gogh)'                         ,
  'Relaxed'                                ,
  'Retro'                                  ,
  'Rezza (terminal.sexy)'                  ,
  'Rippedcasts (Gogh)'                     ,
  'Rippedcasts'                            ,
  'Rosé Pine (Gogh)'                       ,
  'Rosé Pine (base16)'                     ,
  'Rosé Pine Dawn (Gogh)'                  ,
  'Rosé Pine Dawn (base16)'                ,
  'RoséPineDawn (Gogh)'                    ,
  'Rouge 2'                                ,
  'Royal (Gogh)'                           ,
  'Royal'                                  ,
  'Rydgel (terminal.sexy)'                 ,
  'Ryuuko'                                 ,
  'SOS (terminal.sexy)'                    ,
  'Sagelight (base16)'                     ,
  'Sakura (base16)'                        ,
  'Sakura'                                 ,
  'Sandcastle (base16)'                    ,
  'Sat (Gogh)'                             ,
  'Scarlet Protocol'                       ,
  'Sea Shells (Gogh)'                      ,
  'SeaShells'                              ,
  'Seafoam Pastel (Gogh)'                  ,
  'Seafoam Pastel'                         ,
  'Selenized Dark (Gogh)'                  ,
  'Selenized Light (Gogh)'                 ,
  'Sequoia Monochrome'                     ,
  'Sequoia Moonlight'                      ,
  'Sex Colors (terminal.sexy)'             ,
  'Shaman (Gogh)'                          ,
  'Shaman'                                 ,
  'Shapeshifter (base16)'                  ,
  'Shapeshifter (light) (terminal.sexy)'   ,
  'Shel (Gogh)'                            ,
  'Shic (terminal.sexy)'                   ,
  'Silk Light (base16)'                    ,
  'Slate (Gogh)'                           ,
  'Slate'                                  ,
  'SleepyHollow'                           ,
  'Smyck (Gogh)'                           ,
  'Soft Server (Gogh)'                     ,
  'SoftServer'                             ,
  'Solar Flare (base16)'                   ,
  'Solar Flare Light (base16)'             ,
  'Solarized (dark) (terminal.sexy)'       ,
  'Solarized (light) (terminal.sexy)'      ,
  'Solarized Darcula'                      ,
  'Solarized Dark (Gogh)'                  ,
  'Solarized Dark - Patched'               ,
  'Solarized Dark Higher Contrast'         ,
  'Solarized Light (Gogh)'                 ,
  'SolarizedDarcula (Gogh)'                ,
  'SolarizedDark (Gogh)'                   ,
  'SolarizedDarkHigherContrast (Gogh)'     ,
  'SolarizedLight (Gogh)'                  ,
  'SpaceGray'                              ,
  'SpaceGrayEighties (Gogh)'               ,
  'SpaceGrayEightiesDull (Gogh)'           ,
  'Spacedust (Gogh)'                       ,
  'Spacedust'                              ,
  'Spacegray (Gogh)'                       ,
  'Spacemacs (base16)'                     ,
  'Spring'                                 ,
  'Square (Gogh)'                          ,
  'Square'                                 ,
  'Sublette'                               ,
  'Summerfruit Light (base16)'             ,
  'Sundried (Gogh)'                        ,
  'Sundried'                               ,
  'Swayr (terminal.sexy)'                  ,
  'Sweet Love (terminal.sexy)'             ,
  'Synth Midnight Terminal Light (base16)' ,
  'Synthwave Alpha (Gogh)'                 ,
  'Tango (base16)'                         ,
  'Tango (terminal.sexy)'                  ,
  'Tango Adapted'                          ,
  'Tango Half Adapted'                     ,
  'Tangoesque (terminal.sexy)'             ,
  'Tartan (terminal.sexy)'                 ,
  'Terminal Basic (Gogh)'                  ,
  'Terminal Basic'                         ,
  'TerminalBasic (Gogh)'                   ,
  'Terminix Dark (Gogh)'                   ,
  'TerminixDark (Gogh)'                    ,
  'Teva (terminal.sexy)'                   ,
  'The Hulk'                               ,
  'Tin (Gogh)'                             ,
  'Tinacious Design (Light)'               ,
  'Tokyo Night Day'                        ,
  'Tokyo Night Light (Gogh)'               ,
  'TokyoNightLight (Gogh)'                 ,
  'Tomorrow (Gogh)'                        ,
  'Tomorrow (dark) (terminal.sexy)'        ,
  'Tomorrow (light) (terminal.sexy)'       ,
  'Tomorrow Night Burns'                   ,
  'Tomorrow Night Eighties (Gogh)'         ,
  'Tomorrow'                               ,
  'TomorrowNight (Gogh)'                   ,
  'Toy Chest (Gogh)'                       ,
  'ToyChest'                               ,
  'Treehouse (Gogh)'                       ,
  'Treehouse'                              ,
  'Trim Yer Beard (terminal.sexy)'         ,  
  'Twilight (Gogh)'                        ,
  'Twilight (base16)'                      ,
  'Twilight (light) (terminal.sexy)'       ,
  'Twilight'                               ,
  'Ubuntu'                                 ,
  'UltraViolent'                           ,
  'UnderTheSea'                            ,
  'Unikitty Light (base16)'                ,
  'Unikitty Reversible (base16)'           ,
  'Unikitty'                               ,
  'Unsifted Wheat (terminal.sexy)'         ,
  'Ura (Gogh)'                             ,
  'Urple (Gogh)'                           ,
  'Urple'                                  ,
  'VSCodeLight+ (Gogh)'                    ,
  'VWbug (terminal.sexy)'                  ,
  'Vacuous 2 (terminal.sexy)'              ,
  'Vag (Gogh)'                             ,
  'Vaughn (Gogh)'                          ,
  'Vice Alt (base16)'                      ,
  'Vice Dark (base16)'                     ,
  'Violet Dark'                            ,
  'Violet Light'                           ,
  'VisiBlue (terminal.sexy)'               ,
  'VisiBone (terminal.sexy)'               ,
  'Vs Code Light+ (Gogh)'                  ,
  'Warm Neon (Gogh)'                       ,
  'WarmNeon'                               ,
  'Wez (Gogh)'                             ,
  'Wez'                                    ,
  'Whimsy'                                 ,
  'Windows 10 Light (base16)'              ,
  'Windows 95 (base16)'                    ,
  'Windows 95 Light (base16)'              ,
  'Windows High Contrast (base16)'         ,
  'Windows High Contrast Light (base16)'   ,
  'Windows NT Light (base16)'              ,
  'Woodland (base16)'                      ,
  'Wryan (Gogh)'                           ,
  'Wryan'                                  ,
  'Wzoreck (Gogh)'                         ,
  'X::DotShare (terminal.sexy)'            ,
  'X::Erosion (terminal.sexy)'             ,
  'XCode Dusk (base16)'                    ,
  'Yousai (terminal.sexy)'                 ,
  'Zenburn (Gogh)'                         ,
  'Zenburn (base16)'                       ,
  'Zenburn'                                ,
  'aikofog (terminal.sexy)'                ,
  'alacritty'                              ,
  'ayu_light'                              ,
  'carbonfox'                              ,
  'catppuccin-latte'                       ,
  'coffee_theme'                           ,
  'darkermatrix'                           ,
  'darkmatrix'                             ,
  'dawnfox'                                ,
  'dayfox'                                 ,
  'deep'                                   ,
  'dirtysea (base16)'                      ,
  'farmhouse-light'                        ,
  'flexoki-dark'                           ,
  'flexoki-light'                          ,
  'gooey (Gogh)'                           ,
  'hund (terminal.sexy)'                   ,
  'iTerm2 Light Background'                ,
  'iTerm2 Solarized Dark'                  ,
  'iTerm2 Solarized Light'                 ,
  'iTerm2 Tango Light'                     ,
  'iceberg-light'                          ,
  'idea'                                   ,
  'jubi'                                   ,
  'kanagawa (Gogh)'                        ,
  'kokuban (Gogh)'                         ,
  'laserwave (Gogh)'                       ,
  'matrix'                                 ,
  'mono-amber (Gogh)'                      ,
  'mono-cyan (Gogh)'                       ,
  'mono-green (Gogh)'                      ,
  'mono-red (Gogh)'                        ,
  'mono-white (Gogh)'                      ,
  'mono-yellow (Gogh)'                     ,
  'neobones_dark'                          ,
  'neobones_light'                         ,
  'nord-light'                             ,
  'primary'                                ,
  'rose-pine-dawn'                         ,
  's3r0 modified (terminal.sexy)'          ,
  'seoulbones_light'                       ,
  'summercamp (base16)'                    ,
  'terafox'                                ,
  'thwump (terminal.sexy)'                 ,
  'tlh (terminal.sexy)'                    ,
  'tokyonight-day'                         ,
  'tokyonight_day'                         ,
  'vimbones'                               ,
  'vulcan (base16)'                        ,
  'wilmersdorf'                            ,
  'zenbones'                               ,
  'zenbones_light'                         ,
  'zenburn (terminal.sexy)'                ,
  'zenwritten_light'                       ,
}

return scheme_lst.mac

