# 
# layout: orz + arrangement
# 

[ids]
*

[main]
# esc
# f1
# f2
# f3
# f4
# f5
# f6
# f7
# f8
# f9
# f10
# f11
# f12
# ins
# delete

` = 0
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
9 = yen
0 = /
# -
# = ( ^ )
yen = [
backspace = 9

tab = overload(layer01, leftmeta)
q = tab
# w
# e
# r
# t
y = ]
u = ;
i = u
o = i
p = o
[ = p
] = ro
enter = backspace

# capslock ( ctrl by kde config )
# a
# s
# d
# f
# g
h = \
j = h
k = j
l = k
; = l
' = y
\ = '

# leftshift
# z
# x
# c
# v
# b
n = q
m = n
, = m
. = ,
/ = .
ro = enter
# leftshift

# leftcontrol
# ( fn )
leftmeta = overload(layer02, leftmeta)
# leftalt = leftalt
muhenkan = leftshift
space = muhenkan
henkan = space
katakanahiragana = esc
leftshift+leftmeta+f23 = rightcontrol
# left
# up
# down
# right


# 
# layer
# 

# num, emacs
[layer01:M]
# emacs
w = left
e = end

a = home
s = left
d = delete
f = right

# num
i = 6
o = 7
p = 8
[ = 9

k = 2
l = 3
; = 4
' = 5

m = 0
, = 1

# desctop
[layer02:M]
w = C-M-left
e = C-M-right


