
[ids]
*

[main]
# layout: orz + arrangement

# esc
# f1
# f2
# f3
# f4
# f5
# f6
# f7
# f8
# f9
# f10
# f11
# f12
# ins
# delete

` = 0
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
9 = yen
0 = /
# -
# = ( ^ )
yen = [
backspace = 9

tab = leftmeta
q = tab
# w
# e
# r
# t
y = [
u = ;
i = u
o = i
p = o
[ = p
] = ro
enter = backspace

# capslock ( ctrl by kde config )
# a
# s
# d
# f
# g
h = \
j = h
k = j
l = k
; = l
' = y
\ = '

# leftshift
# z
# x
# c
# v
# b
n = q
m = n
, = m
. = ,
/ = .
ro = enter
# leftshift

# leftcontrol
# ( fn )
# leftmeta
# leftalt
muhenkan = leftshift
# space
henkan = muhenkan
katakanahiragana = esc
# f23 = 
# left
# up
# down
# right

