#!/bin/bash

# function mb_cnv_symbol

srch= '！＃＄％＆＊＋－＝：；？＠／＼＾＿｀～'
rpl=  '!#$%&*+-=:;?@/\^_`~'

cat -            |\
sed_y $srch $rpl |\
sed               \
  -e "s|・| |g"   \
  -e "s/｜/|/g"   \
  -e "s|＇|'|g"   \
  -e 's|＂|"|g'   \
                  \
  -e "s|（| (|g"  \
  -e "s|）|) |g"  \
  -e "s|＜| <|g"  \
  -e "s|＞|> |g"  \
  -e "s|｛| {|g"  \
  -e "s|｝|} |g"  \
  -e 's|［| [|g'  \
  -e 's|］|] |g'  \
                  \
  -e "s|、|, |g"  \
  -e "s|。|. |g"  \
  -e "s|，|, |g"  \
  -e "s|．|. |g"  \
                  \
  -e "s|「||g"    \
  -e "s|」| |g"   \
  -e "s|『||g"    \
  -e "s|』| |g"   \



