#!/bin/bash

dir=~/wrk

cmdsub="$1"

if   test $cmdsub = 'cd'
then
  psh $dir

elif test $cmdsub = 'fd'
then
  if test -z $2
  then
    fd -e md '' $dir
  else
    fd -e md '' $dir | rg $2
  fi

elif test $cmdsub = 'rg'
then
  rg -N -g '*.md' "$2" $dir/

elif test $cmdsub = 'pw'

  rg -N -g '*.md' 'pw' $dir/ -B3

elif test $cmdsub = 'vi'
then
  if test -z $2
  then
    vi -p -c ":cd $dir"
  else
    vi -p -c ":cd $dir" $( fd -e md '' $dir | rg $2 )
  fi
fi

